### ISSUE TITLE
Help needed running the project

### ISSUE THREAD

**Issue by ravi8x** [pepebecker/chat-sdk-admin-api#1]
Hi

I was trying to run the project by `npm start` however I am getting errors due to missing values in **serviceAccountKey.js**. I tried inserting few env variable but still no luck.

Do you have any sample data that shows the values of the variables needed.
```
module.exports = {
  type: process.env.CS_API_FB_TYPE,
  project_id: process.env.CS_API_FB_PROJECT_ID,
  private_key_id: process.env.CS_API_FB_PRIVATE_KEY_ID,
  private_key: process.env.CS_API_FB_PRIVATE_KEY.split('\\n').join('\n'),
  client_email: process.env.CS_API_FB_CLIENT_EMAIL,
  client_id: process.env.CS_API_FB_CLIENT_ID,
  auth_uri: process.env.CS_API_FB_AUTH_URI,
  token_uri: process.env.CS_API_FB_TOKEN_URI,
  auth_provider_x509_cert_url: process.env.CS_API_FB_AUTH_PROPVIDER_CERT_URL,
  client_x509_cert_url: process.env.CS_API_FB_CLIENT_CERT_URL,
  databaseURL: process.env.CS_API_FB_DATABASE_URL
}
```

**Comment by Famin42** [comment]
I'm stuck on this step too.

**Comment by ravi8x** [comment]
The `serviceAccountKey.js` can be found on Firebase Admin Console.

1. Click on **gear icon** next to **Project Overview.**
2. Click on **Service Accounts**.
3. Select **Node.js** and click **generate new private key**.
4. Now you can **download** the file and the content of serviceAccountKey.js can be found in this file.
